# Generated by Django 5.2.1 on 2025-05-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='firm_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
