# Generated by Django 5.2.1 on 2025-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True, help_text='Is the firm active?')),
                ('flow', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
