# Generated by Django 5.2.1 on 2025-05-25 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0002_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firm',
            name='first_step',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
